server:
  port: 8084

spring:
  application:
    name: message-service
  
  data:
    mongodb:
      uri: mongodb+srv://revjobs_admin:Vishnu%40123@revjobs-cluster.lyip45g.mongodb.net/revjobs_messages?retryWrites=true&w=majority&appName=revjobs-cluster

  cloud:
    discovery:
      enabled: true

logging:
  level:
    org.springframework.web: DEBUG
    com.netflix.discovery: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

